// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const main: string;
export const topLogo: string;
export const youtubeBox: string;
export const back: string;
