// This file is automatically generated from your CSS. Any edits will be overwritten.
export const headerWrapper: string;
export const isScrolled: string;
export const header: string;
export const logo: string;
export const active: string;
